-- begin PETCLINIC_OWNER
create unique index IDX_PETCLINIC_OWNER_UK_EMAIL on PETCLINIC_OWNER (EMAIL) where DELETE_TS is null ^
create unique index IDX_PETCLINIC_OWNER_UK_PHONE_NUMBER on PETCLINIC_OWNER (PHONE_NUMBER) where DELETE_TS is null ^
-- end PETCLINIC_OWNER
-- begin PETCLINIC_PET
alter table PETCLINIC_PET add constraint FK_PETCLINIC_PET_ON_TYPE foreign key (TYPE_ID) references PETCLINIC_PET_TYPE(ID)^
alter table PETCLINIC_PET add constraint FK_PETCLINIC_PET_ON_OWNER foreign key (OWNER_ID) references PETCLINIC_OWNER(ID)^
create index IDX_PETCLINIC_PET_ON_TYPE on PETCLINIC_PET (TYPE_ID)^
create index IDX_PETCLINIC_PET_ON_OWNER on PETCLINIC_PET (OWNER_ID)^
-- end PETCLINIC_PET
-- begin PETCLINIC_VETERINARIAN
alter table PETCLINIC_VETERINARIAN add constraint FK_PETCLINIC_VETERINARIAN_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_PETCLINIC_VETERINARIAN_ON_USER on PETCLINIC_VETERINARIAN (USER_ID)^
-- end PETCLINIC_VETERINARIAN
-- begin PETCLINIC_VISIT
alter table PETCLINIC_VISIT add constraint FK_PETCLINIC_VISIT_ON_PET foreign key (PET_ID) references PETCLINIC_PET(ID)^
alter table PETCLINIC_VISIT add constraint FK_PETCLINIC_VISIT_ON_VETERINARIAN foreign key (VETERINARIAN_ID) references PETCLINIC_VETERINARIAN(ID)^
create index IDX_PETCLINIC_VISIT_ON_PET on PETCLINIC_VISIT (PET_ID)^
create index IDX_PETCLINIC_VISIT_ON_VETERINARIAN on PETCLINIC_VISIT (VETERINARIAN_ID)^
-- end PETCLINIC_VISIT
-- begin PETCLINIC_VISIT_CONSUMABLE_LINK
alter table PETCLINIC_VISIT_CONSUMABLE_LINK add constraint FK_VISCON_ON_VISIT foreign key (VISIT_ID) references PETCLINIC_VISIT(ID)^
alter table PETCLINIC_VISIT_CONSUMABLE_LINK add constraint FK_VISCON_ON_CONSUMABLE foreign key (CONSUMABLE_ID) references PETCLINIC_CONSUMABLE(ID)^
-- end PETCLINIC_VISIT_CONSUMABLE_LINK
-- begin PETCLINIC_CONSUMABLE
create unique index IDX_PETCLINIC_CONSUMABLE_UK_TITLE on PETCLINIC_CONSUMABLE (TITLE) where DELETE_TS is null ^
-- end PETCLINIC_CONSUMABLE
