alter table PETCLINIC_VETERINARIAN add constraint FK_PETCLINIC_VETERINARIAN_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_PETCLINIC_VETERINARIAN_ON_USER on PETCLINIC_VETERINARIAN (USER_ID);
