alter table PETCLINIC_VISIT add constraint FK_PETCLINIC_VISIT_ON_PET foreign key (PET_ID) references PETCLINIC_PET(ID);
alter table PETCLINIC_VISIT add constraint FK_PETCLINIC_VISIT_ON_VETERINARIAN foreign key (VETERINARIAN_ID) references PETCLINIC_VETERINARIAN(ID);
create index IDX_PETCLINIC_VISIT_ON_PET on PETCLINIC_VISIT (PET_ID);
create index IDX_PETCLINIC_VISIT_ON_VETERINARIAN on PETCLINIC_VISIT (VETERINARIAN_ID);
